/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Get started',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'End user',
          items: [
            'roles/user/metamask',
          ],
        },
        {
          type: 'category',
          label: 'Node operator',
          items: [
            'roles/node/join',
            'roles/node/join-genesis',
            'roles/node/basic',
            'roles/node/ust-to-evm',
            'roles/node/ust-from-evm',
            'roles/node/axl-to-evm',
            'roles/node/axl-from-evm',
          ],
        },
        {
          type: 'category',
          label: 'Validator',
          items: [
            {
              type: 'category',
              label: 'Setup',
              items: [
                'roles/validator/setup/overview',
                'roles/validator/setup/vald-tofnd',
                'roles/validator/setup/backup',
                'roles/validator/setup/register-broadcaster',
                'roles/validator/setup/stake-axl',
                'roles/validator/setup/health-check',
              ],
            },
            {
              type: 'category',
              label: 'Support external chains',
              items: [
                'roles/validator/external-chains/overview',
                'roles/validator/external-chains/avalanche',
                'roles/validator/external-chains/ethereum',
                'roles/validator/external-chains/fantom',
                'roles/validator/external-chains/moonbeam',
                'roles/validator/external-chains/polygon',
              ],
            },
            {
              type: 'category',
              label: 'Troubleshoot',
              items: [
                'roles/validator/troubleshoot/recovery',
                'roles/validator/troubleshoot/startup',
                'roles/validator/troubleshoot/leave',
                'roles/validator/troubleshoot/unjail',
                'roles/validator/troubleshoot/missed-too-many-blocks',
              ],
            },
          ],
        },
        'roles/dev',
      ],
    },
    {
      type: 'category',
      label: 'Releases',
      collapsible: true,
      collapsed: false,
      items: [
        'releases/mainnet',
        'releases/testnet',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsible: true,
      collapsed: false,
      items: [
        'reference/extra-commands',
        'reference/useful-links',
        {
          type: 'category',
          label: 'Technical FAQ',
          items: [
            'reference/faq/help',
            'reference/faq/problem1',
            'reference/faq/problem2',
            'reference/faq/problem3',
            'reference/faq/problem4',
            'reference/faq/problem5',
            'reference/faq/problem6',
            'reference/faq/problem7',
            'reference/faq/problem8',
            'reference/faq/ex5-problem',
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
